export const INGREDIENT_DISPLAY_NAMES: Record<string, string> = {
  heart_plate: '하트 모양 접시',
  cupid_decoration: '큐피드 장식',
  napkin: '냅킨',
  paper_napkin: '종이 냅킨',
  cotton_napkin: '면 냅킨',
  linen_napkin: '린넨 냅킨',
  plastic_tray: '플라스틱 쟁반',
  wooden_tray: '나무 쟁반',
  plastic_plate: '플라스틱 접시',
  plastic_cup: '플라스틱 컵',
  ceramic_plate: '도자기 접시',
  ceramic_cup: '도자기 컵',
  plastic_wine_glass: '플라스틱 와인잔',
  glass_wine_glass: '유리 와인잔',
  vase_with_flowers: '꽃병 장식',
  wine: '와인',
  premium_steak: '프리미엄 스테이크',
  coffee: '커피',
  fresh_salad: '신선한 샐러드',
  scrambled_eggs: '에그 스크램블',
  bacon: '베이컨',
  bread: '빵',
  champagne_bottle: '샴페인',
  baguette: '바게트빵',
  coffee_pot: '커피 포트',
  cake_base: '케이크 시트',
  buttercream_frosting: '버터크림',
  fresh_berries: '신선한 베리',
  fondant: '폰단트',
  edible_gold_leaf: '식용 금박',
  chocolate_ganache: '초콜릿 가나슈',
  cake_board: '케이크 보드',
  edible_flowers: '식용 꽃',
}

export const MENU_INGREDIENTS: Record<string, Record<string, Record<string, number>>> = {
  valentine: {
    simple: { heart_plate: 1, cupid_decoration: 1, paper_napkin: 1, plastic_tray: 1, plastic_wine_glass: 1, wine: 1, premium_steak: 1 },
    grand: { heart_plate: 1, cupid_decoration: 2, cotton_napkin: 1, wooden_tray: 1, plastic_wine_glass: 1, wine: 1, premium_steak: 1 },
    deluxe: { heart_plate: 1, cupid_decoration: 3, linen_napkin: 2, wooden_tray: 1, vase_with_flowers: 1, glass_wine_glass: 1, wine: 1, premium_steak: 1 },
  },
  french: {
    simple: { plastic_plate: 1, plastic_cup: 1, paper_napkin: 1, plastic_tray: 1, plastic_wine_glass: 1, coffee: 1, wine: 1, fresh_salad: 1, premium_steak: 1 },
    grand: { ceramic_plate: 1, ceramic_cup: 1, cotton_napkin: 1, wooden_tray: 1, plastic_wine_glass: 1, coffee: 1, wine: 1, fresh_salad: 1, premium_steak: 1 },
    deluxe: { ceramic_plate: 1, ceramic_cup: 1, linen_napkin: 1, wooden_tray: 1, vase_with_flowers: 1, glass_wine_glass: 1, coffee: 1, wine: 1, fresh_salad: 1, premium_steak: 1 },
  },
  english: {
    simple: { plastic_plate: 1, plastic_cup: 1, paper_napkin: 1, plastic_tray: 1, scrambled_eggs: 1, bacon: 2, bread: 1, premium_steak: 1 },
    grand: { ceramic_plate: 1, ceramic_cup: 1, cotton_napkin: 1, wooden_tray: 1, scrambled_eggs: 2, bacon: 3, bread: 1, premium_steak: 1 },
    deluxe: { ceramic_plate: 1, ceramic_cup: 1, linen_napkin: 1, wooden_tray: 1, vase_with_flowers: 1, scrambled_eggs: 2, bacon: 4, bread: 2, premium_steak: 1 },
  },
  champagne: {
    grand: { ceramic_plate: 2, ceramic_cup: 2, cotton_napkin: 2, wooden_tray: 1, plastic_wine_glass: 2, champagne_bottle: 1, baguette: 4, coffee_pot: 1, wine: 1, premium_steak: 2 },
    deluxe: { ceramic_plate: 2, ceramic_cup: 2, linen_napkin: 2, wooden_tray: 1, vase_with_flowers: 1, glass_wine_glass: 2, champagne_bottle: 1, baguette: 4, coffee_pot: 1, wine: 1, premium_steak: 2 },
  },
  cake: {
    simple: { cake_base: 1, buttercream_frosting: 1, fresh_berries: 1, cake_board: 1, plastic_plate: 1, plastic_tray: 1, paper_napkin: 1 },
    grand: { cake_base: 1, buttercream_frosting: 1, fondant: 1, fresh_berries: 1, cake_board: 1, ceramic_plate: 1, ceramic_cup: 1, cotton_napkin: 1, wooden_tray: 1 },
    deluxe: {
      cake_base: 1,
      buttercream_frosting: 1,
      fondant: 1,
      edible_gold_leaf: 1,
      chocolate_ganache: 1,
      edible_flowers: 1,
      cake_board: 1,
      ceramic_plate: 1,
      ceramic_cup: 1,
      linen_napkin: 1,
      wooden_tray: 1,
      vase_with_flowers: 1,
    },
  },
}

export const TABLEWARE_CODES = new Set<string>([
  'heart_plate',
  'cupid_decoration',
  'paper_napkin',
  'napkin',
  'cotton_napkin',
  'linen_napkin',
  'plastic_tray',
  'wooden_tray',
  'plastic_plate',
  'plastic_cup',
  'ceramic_plate',
  'ceramic_cup',
  'plastic_wine_glass',
  'glass_wine_glass',
  'cake_board',
  'vase_with_flowers',
])


